@startuml

entity "Пользователь" {
  + id : Integer <<PK>>
  + email : String
  + acl : String
}

entity "Проем" {
  + id : Integer <<PK>>
  + высота_между_этажами : Integer
  + ширина_проема : Integer
  + длина_проема : Integer
  + допустимая_длина_основания_под_лестницц : Integer
  + толщина_перекрытия : Integer
  + тип_лестницы : String
  + форма_проема : String
}

entity "Критерии_удобства" {
  + id : Integer <<PK>>
  + высота_подъема_ступени_min : Integer
  + высота_подъема_ступени_max : Integer
  + глубина_ступени_min : Integer
  + глубина_ступени_max : Integer
  + свободное_пространство_над_лестницей_min : Integer
  + свободное_пространство_над_лестницей_max : Integer
  + свес_ступени_min : Integer
  + свес_ступени_max : Integer
  + ширина_марша_min : Integer
  + ширина_марша_max : Integer
  + формула_блонделя_min : Integer
  + формула_блонделя_max : Integer
}

entity "Лестница" {
  + id : Integer <<PK>>
  + тип : String
  + материал : String
  + конструктивное_исполнение : String
  + ширина_марша : Integer
  + высота_ступени : Integer
  + глубина_ступени : Integer
  + угол_наклона : Integer
  + количество_ступеней : Integer
}

entity "Конфигурация" {
  + id : Integer <<PK>>
  + коэффициент_комфорта : Float
  + формула_удобства : Float
  + формула_блонделя : Float
  + свободное_пространство_над_лестницей : Integer
  + минимальная_ширина_косоура : Integer
  + проем_id : Integer <<FK>>
  + критерии_удобства_id : Integer <<FK>>
  + лестница_id : Integer <<FK>>
}

entity "Результат_расчета" {
  + id : Integer <<PK>>
  + конфигурация_id : Integer <<FK>>
  + пользователь_id : Integer <<FK>>
}

' Определение связей между сущностями
Пользователь ||--o{ Результат_расчета : "содержит ограничения"
Проем ||--|| Конфигурация : "содержит"
Критерии_удобства ||--|| Конфигурация : "содержит"
Лестница ||--|| Конфигурация : "содержит"
Результат_расчета ||--o{ Конфигурация : "генерирует"

@enduml
