@startuml

entity "requests" as requests {
    *id : SERIAL PRIMARY KEY
    --
    *user_id : INTEGER NOT NULL
    *status : ENUM VARCHAR ('new', 'processing', 'ready', 'send') NOT NULL
    *request_data : JSON NOT NULL
    *progress_percent : DECIMAL
    *create_time : TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    *update_time : TIMESTAMP DEFAULT CURRENT_TIMESTAMP
}

entity "optimal_configurations" as optimal_configurations {
    *request_id : INTEGER NOT NULL
    --
    *configurations : JSON NOT NULL
}
optimal_configurations }--|{ requests : request_id

entity "users" as users {
    *id : INTEGER SERIAL PRIMARY KEY
    --
    *email : VARCHAR(128) NOT NULL PRIMARY KEY
    *update_time : TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    *acl_max_simultaneous_requests : INTEGER
    *acl_available_calculations_count : INTEGER
}
users }--|{ requests : request_id

@enduml
